### PR TITLE
APA102/DotStar LEDs 

### PR DESCRIPTION
**Pull request by mdiehm**
Implementation of APA102/DotStar LEDs w/ almost same interface as found in micropython for ESP8266 (https://docs.micropython.org/en/latest/esp8266/tutorial/apa102.html). Tweaked their example demo a bit but tried to stay close and consistant.

Updated tutorial but kept the original LED text. Do we want to get rid of it? 

Not sure if we also want a read() method to get the LEDs status but not sure what we would use it for at this point...

### CODE REVIEW

**Comment by SebastianRoll** [comment]
Really awesome!! I'm assuming the code is tested with your *the pad*, so I say it's ready for merge.

> Updated tutorial but kept the original LED text. Do we want to get rid of it?

Not sure what is mean with original LED text. Maybe I'm too sleepy to understand:)

**Comment by mdiehm** [comment]
> Really awesome!! I'm assuming the code is tested with your _the pad_, so I say it's ready for merge.

Yes the disco has been playing up and down on the_pad here (;

> > Updated tutorial but kept the original LED text. Do we want to get rid of it?
> 
> Not sure what is mean with original LED text. Maybe I'm too sleepy to understand:)

You already had some explanation how to interact with the LED on Pin(19) with some explanation of PWM which I find interesting and worth keeping. Just not sure if you think the same.

**Comment by SebastianRoll** [comment]
Let's get it merged in!

**Review by kaffelars — APPROVED** [review]
Looks great!

**Pull request merged**
